### ISSUE TITLE
--cache support?

### ISSUE THREAD

**Issue by dakorpar** [chekalsky/phpcs-action#13]
on medium/big sized projects running with --cache flag speeds it a lot...
Support based on cache from master/previous build on branch would speed it up a lot

**Comment by jrfnl** [comment]
Just some input from the perspective of someone who has looked in-depth into the caching implementation in PHPCS:

The `--cache` option is not very practical for GH Actions.

PHPCS would (should) normally only be run _once_ per workflow/actions run, as generally speaking all sniffs are set up to give the same results independently of the PHP version which is used to run PHPCS.

If using the `cache` option when doing so, the resulting cache file would have to be uploaded as an artifact.
In a next run, the previous cache file would need to be downloaded first, put in the location were it is expected to be and a PHPCS run executed after that would then benefit from it.

A first run with the `--cache` argument, i.e. when there is no existing cache file, is actually a lot slower than a normal run as the cache file needs to be build and written to disk.

So, using the `--cache` argument in the action would in actual fact _slow down_ execution a lot.
It would only be beneficial for subsequent runs and only if combined with the artifact upload/download.

Also the cache "save" location can be set in a custom ruleset, so the action would need to either read the ruleset to see if a cache location is set or set a location on the command-line overruling a potentially set "save" location from a custom ruleset, as otherwise it would not necessarily be able to find the cache file to upload.

All in all, this is not as easy as it sounds and may not actually give any real benefits time-wise in a CI set-up.

It may be more beneficial to always run with the `--no-cache` option as it would prevent the slow down from a cache file being build which will never be used, if the cache option is enabled in a custom ruleset.

**Comment by dakorpar** [comment]
building cache file shouldn't really cost that much that you would feel slowdown...
We're using something like this on circleci and it speed up our build a lot.
Nevermind different branches here, project has 10k plus files to being tested and only couple of them are changed on every PR, even if it's 100+ it's still massive speed up.

```
      - restore_cache:
          keys:
            - phpcs-cache-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
      - run: composer run qa
      - save_cache:
          paths:
            - .phpcs-cache.json
          key: phpcs-cache-{{ .BuildNum }}
```

**Comment by jrfnl** [comment]
I'm not saying it shouldn't be done. I'm just saying that just enabling `--cache` is not a good idea and that any implementation of this will need to handle upload/download of artifacts + take custom ruleset configurations into account.
